cluster:
  name: ${CLUSTER_NAME}
node:
  name: ${ELASTICSEARCH_NODE_NAME}
  data: true
path:
  data: /usr/share/elasticsearch/es-data
  logs: /usr/share/elasticsearch/es-log
  plugins: /usr/share/elasticsearch/plugins
  work: /usr/share/elasticsearch/es-work
network:
  host: ${NETWORK_BIND_HOST}
  publish_host: ${NETWORK_PUBLISH_HOST}
discovery:
  type: ec2
  zen:
    ping:
      multicast:
        enabled: false
  ec2:
    tag:
      Name: ${EC2_TAG_NODE_NAME}  
plugin:
  mandatory: cloud-aws
cloud:
  node:
    auto_attributes: true
  aws:
    region: eu-west-1
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_KEY}
repositories:
  s3:
    bucket: ${ES_S3_BUCKET_NAME}
    region: eu-west-1
gateway:
  recover_after_nodes: 1
  recover_after_time: 1m
  expected_nodes: 3     
index:
  number_of_shards: ${NUMBER_OF_SHARDS}
  number_of_replicas: ${NUMBER_OF_REPLICAS}
bootstrap:
  mlockall: true